'use client';

import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';

const inputClass = 'w-full rounded-xl border border-[var(--border-default)] bg-[var(--input-bg)] px-3.5 py-3 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--accent)]';

function inputDate(epoch) {
  if (!epoch) return '';
  const date = new Date(epoch * 1000);
  return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
}

function Participation({ contest, signedIn, mutate, busy }) {
  const [blogs, setBlogs] = useState([]);
  const [blogId, setBlogId] = useState('');
  const [manual, setManual] = useState(false);
  useEffect(() => {
    if (!signedIn || contest.status !== 'live') return;
    fetch('/api/blogs/list?status=published').then((response) => response.ok ? response.json() : null).then((data) => setBlogs(data?.blogs || [])).catch(() => {});
  }, [contest.status, signedIn]);
  return <section id="enter-contest" className="overflow-hidden rounded-3xl border border-[var(--accent)]/25 bg-[linear-gradient(135deg,var(--card-bg),var(--accent-subtle))] shadow-sm">
    <div className="grid gap-0 lg:grid-cols-[minmax(0,0.9fr)_minmax(360px,1.1fr)]">
      <div className="p-6 sm:p-8">
        <span className="inline-flex items-center gap-2 rounded-full bg-[var(--card-bg)] px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--accent)]"><ion-icon name="trophy-outline" /> Competitive entry</span>
        <h2 className="mt-4 font-serif text-3xl font-extrabold text-[var(--text-primary)]">Enter this contest</h2>
        <p className="mt-2 max-w-xl text-sm leading-6 text-[var(--text-muted)]">Submit one of your published LixBlogs stories. We freeze the submitted revision for fair judging while the original remains under your ownership.</p>
        <dl className="mt-6 grid gap-3 sm:grid-cols-3">
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--card-bg)] p-3"><dt className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-faint)]">Required topics</dt><dd className="mt-1.5 text-xs font-semibold text-[var(--text-secondary)]">{contest.requiredTopics.join(', ') || 'None'}</dd></div>
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--card-bg)] p-3"><dt className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-faint)]">Entry limit</dt><dd className="mt-1.5 text-xs font-semibold text-[var(--text-secondary)]">{contest.perAuthorLimit} per author</dd></div>
          <div className="rounded-xl border border-[var(--border-default)] bg-[var(--card-bg)] p-3"><dt className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-faint)]">Publication</dt><dd className="mt-1.5 text-xs font-semibold text-[var(--text-secondary)]">{contest.allowedTargets.join(', ') || 'Any public target'}</dd></div>
        </dl>
      </div>
      <div className="border-t border-[var(--border-default)] bg-[var(--card-bg)] p-6 sm:p-8 lg:border-l lg:border-t-0">
        {contest.status === 'live' && signedIn && <div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-[var(--accent)]">Choose your entry</p><label className="mt-3 block text-xs font-bold text-[var(--text-secondary)]">Published blog{manual ? <input value={blogId} onChange={(event) => setBlogId(event.target.value)} className={`${inputClass} mt-2`} placeholder="Paste a blog ID" /> : <select value={blogId} onChange={(event) => setBlogId(event.target.value)} className={`${inputClass} mt-2`}><option value="">Select a published blog…</option>{blogs.map((blog) => <option key={blog.id} value={blog.id}>{blog.title || 'Untitled'} · {blog.slug}</option>)}</select>}</label><button type="button" onClick={() => { setManual((value) => !value); setBlogId(''); }} className="mt-2 text-xs font-semibold text-[var(--accent)]">{manual ? 'Choose from my published blogs' : 'Enter a blog ID instead'}</button><button disabled={!blogId || busy} onClick={() => mutate(`/api/contests/${contest.slug}/submissions`, { blogId })} className="mt-5 w-full rounded-xl bg-[var(--accent)] px-5 py-3 text-sm font-bold text-white shadow-sm disabled:opacity-50">Submit frozen revision</button><p className="mt-3 text-[11px] leading-5 text-[var(--text-faint)]">Review your live post first. Later edits will not change the judged snapshot.</p></div>}
        {contest.status !== 'live' && <div className="grid min-h-44 place-items-center rounded-2xl border border-dashed border-[var(--border-default)] bg-[var(--bg-surface)] p-6 text-center"><div><ion-icon name={contest.status === 'scheduled' ? 'time-outline' : 'lock-closed-outline'} style={{ fontSize: '28px', color: 'var(--accent)' }} /><p className="mt-3 text-sm font-bold text-[var(--text-primary)]">{contest.status === 'scheduled' ? 'Entries are not open yet' : 'Entries are closed'}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{contest.status === 'scheduled' ? 'Come back when the contest begins.' : 'Browse the submitted work in the Leaderboard tab.'}</p></div></div>}
        {!signedIn && contest.status === 'live' && <div className="grid min-h-44 place-items-center text-center"><div><p className="text-sm font-bold text-[var(--text-primary)]">Sign in to submit your work</p><p className="mt-2 text-xs text-[var(--text-muted)]">You will return to this contest after authentication.</p><a href={`/sign-in?next=${encodeURIComponent(`/contests/${contest.slug}`)}`} className="mt-5 inline-flex rounded-full bg-[var(--accent)] px-5 py-2.5 text-sm font-bold text-white">Sign in to participate</a></div></div>}
      </div>
    </div>
  </section>;
}

export default function ContestControls({ contest, members, submissions, signedIn, compact = false }) {
  const router = useRouter();
  const manager = contest.viewerRole === 'organizer' || contest.viewerRole === 'moderator';
  const judge = contest.viewerRole === 'organizer' || contest.viewerRole === 'judge';
  const tabs = [...(manager ? [{ id: 'branding', label: 'Branding', icon: 'color-palette-outline' }, { id: 'brief', label: 'Brief & rules', icon: 'document-text-outline' }, { id: 'eligibility', label: 'Eligibility', icon: 'shield-checkmark-outline' }, { id: 'schedule', label: 'Schedule', icon: 'calendar-outline' }] : []), ...(contest.viewerRole === 'organizer' ? [{ id: 'team', label: 'Team', icon: 'people-outline' }] : []), ...(judge ? [{ id: 'judging', label: 'Judging', icon: 'ribbon-outline' }] : []), ...(manager ? [{ id: 'danger', label: 'Danger zone', icon: 'warning-outline' }] : [])];
  const [activeTab, setActiveTab] = useState(manager ? 'branding' : 'judging');
  const [member, setMember] = useState('');
  const [role, setRole] = useState('judge');
  const [draft, setDraft] = useState({ slug: contest.slug, title: contest.title, description: contest.description, problemStatement: contest.problemStatement, rules: contest.rules, theme: contest.theme, coverUrl: contest.coverUrl || '', templateContent: contest.templateContent, tags: contest.tags.join(', '), requiredTopics: contest.requiredTopics.join(', '), allowedTargets: contest.allowedTargets.join(', '), perAuthorLimit: contest.perAuthorLimit, minimumAccountAgeMonths: contest.eligibility.minimumAccountAgeMonths ?? Math.ceil(Number(contest.eligibility.minimumAccountAgeDays || 0) / 30), requireBio: Boolean(contest.eligibility.requireBio), startsAt: inputDate(contest.startsAt), submissionsCloseAt: inputDate(contest.submissionsCloseAt), judgingClosesAt: inputDate(contest.judgingClosesAt) });
  const [winner, setWinner] = useState('');
  const [runnerUp, setRunnerUp] = useState('');
  const [honorable, setHonorable] = useState('');
  const [busy, setBusy] = useState('');
  const [message, setMessage] = useState('');

  async function mutate(path, body, method = 'POST', success = 'Saved.') {
    setBusy(path); setMessage('');
    try {
      const response = await fetch(path, { method, headers: body ? { 'content-type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) { setMessage(result.error || 'The request failed'); return false; }
      setMessage(success);
      if (method === 'DELETE' && path === `/api/contests/${contest.slug}`) { router.push('/contests'); return true; }
      if (method === 'PATCH' && result.slug && result.slug !== contest.slug) {
        router.replace(`/contests/${result.slug}?tab=manage`);
        return true;
      }
      router.refresh(); return true;
    } catch { setMessage('The request failed. Check your connection and try again.'); return false; }
    finally { setBusy(''); }
  }

  if (compact || (!manager && !judge)) return <div className="space-y-3"><Participation contest={contest} signedIn={signedIn} mutate={mutate} busy={busy} />{message && <p role="status" className="rounded-xl bg-[var(--bg-surface)] p-3 text-xs text-[var(--text-secondary)]">{message}</p>}</div>;

  return <section className="overflow-hidden rounded-3xl border border-[var(--border-default)] bg-[var(--card-bg)] shadow-sm">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-[var(--divider)] px-5 py-5 sm:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">Contest workspace</p><h2 className="mt-1 font-serif text-2xl font-extrabold text-[var(--text-primary)]">Manage contest</h2></div><div className="flex items-center gap-2"><span className="rounded-full bg-[var(--bg-surface)] px-3 py-1.5 text-xs font-semibold capitalize text-[var(--text-muted)]">{contest.viewerRole === 'moderator' ? 'co-host' : contest.viewerRole}</span>{contest.configuredStatus === 'draft' && manager && <button disabled={busy} onClick={() => mutate(`/api/contests/${contest.slug}`, { action: 'publish' }, 'PATCH', 'Contest published.')} className="rounded-full bg-emerald-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">Publish contest</button>}</div></header>
    <div className="grid lg:grid-cols-[minmax(0,1fr)_230px]">
      <div className="min-w-0 p-5 sm:p-8">
    {activeTab === 'branding' && <div><h2 className="font-serif text-2xl font-bold text-[var(--text-primary)]">Branding and identity</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Shape how the contest appears across discovery, sharing, and its public page.</p>{draft.coverUrl && <div className="mt-6 overflow-hidden rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><img src={draft.coverUrl} alt="Current contest cover" className="h-48 w-full object-cover" /></div>}<div className="mt-6 grid gap-5"><label className="text-xs font-bold text-[var(--text-secondary)]">Contest title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className={`${inputClass} mt-2`} placeholder="A clear, memorable contest title" /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Public URL slug<input disabled={contest.configuredStatus !== 'draft' || contest.viewerRole !== 'organizer'} value={draft.slug} onChange={(event) => setDraft({ ...draft, slug: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '') })} className={`${inputClass} mt-2 disabled:opacity-60`} placeholder="contest-url-slug" /><span className="mt-1 block font-normal text-[var(--text-faint)]">Only the organizer can change this while the contest is a private draft.</span></label><label className="text-xs font-bold text-[var(--text-secondary)]">Short description<textarea rows={4} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} className={`${inputClass} mt-2 resize-y leading-6`} placeholder="A concise summary shown on contest cards and search previews." /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Theme<input value={draft.theme} onChange={(event) => setDraft({ ...draft, theme: event.target.value })} className={`${inputClass} mt-2`} placeholder="Technology for public good" /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Discovery tags<input value={draft.tags} onChange={(event) => setDraft({ ...draft, tags: event.target.value })} className={`${inputClass} mt-2`} placeholder="technology, community, future" /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Cover image URL<input type="url" pattern="https://.*" value={draft.coverUrl} onChange={(event) => setDraft({ ...draft, coverUrl: event.target.value })} className={`${inputClass} mt-2`} placeholder="https://example.com/contest-cover.jpg" /></label></div><button disabled={busy} onClick={() => mutate(`/api/contests/${contest.slug}`, { slug: draft.slug, title: draft.title, description: draft.description, theme: draft.theme, coverUrl: draft.coverUrl, tags: draft.tags.split(',').map((item) => item.trim()).filter(Boolean) }, 'PATCH', 'Contest branding saved.')} className="mt-7 rounded-full bg-[var(--accent)] px-6 py-2.5 text-sm font-bold text-white disabled:opacity-50">Save branding</button></div>}
    {activeTab === 'brief' && <div><h2 className="font-serif text-2xl font-bold text-[var(--text-primary)]">Brief, rules, and template</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Give entrants enough context to produce focused, eligible work. Every field supports Markdown.</p><div className="mt-6 grid gap-7">{[['problemStatement', 'Problem statement', '## The challenge\n\nExplain the question writers should answer and what a strong entry should cover.'], ['rules', 'Rules', '## Entry requirements\n\n1. Publish original work.\n2. Credit external sources.\n3. Submit before the deadline.'], ['templateContent', 'Optional writing template', '# Opening\n\n## Main argument\n\n## Sources and conclusion']].map(([key, label, placeholder]) => <label key={key} className="text-xs font-bold text-[var(--text-secondary)]"><span className="flex items-center justify-between gap-2"><span>{label}</span><span className="font-normal text-[var(--accent)]">Markdown supported</span></span><textarea rows={10} value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} placeholder={placeholder} className={`${inputClass} mt-2 min-h-56 resize-y font-mono text-[15px] leading-7`} /></label>)}</div><button disabled={busy} onClick={() => mutate(`/api/contests/${contest.slug}`, { problemStatement: draft.problemStatement, rules: draft.rules, templateContent: draft.templateContent }, 'PATCH', 'Contest brief saved.')} className="mt-7 rounded-full bg-[var(--accent)] px-6 py-2.5 text-sm font-bold text-white disabled:opacity-50">Save brief</button></div>}
    {activeTab === 'eligibility' && <div><h2 className="font-serif text-2xl font-bold text-[var(--text-primary)]">Entry eligibility</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Control which published blogs and authors may enter.</p><div className="mt-6 grid gap-5"><label className="text-xs font-bold text-[var(--text-secondary)]">Required blog topics<input value={draft.requiredTopics} onChange={(event) => setDraft({ ...draft, requiredTopics: event.target.value })} className={`${inputClass} mt-2`} placeholder="open-source, education, community" /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Allowed publication targets<input value={draft.allowedTargets} onChange={(event) => setDraft({ ...draft, allowedTargets: event.target.value })} className={`${inputClass} mt-2`} placeholder="personal, org:organization-id" /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Minimum account age (months)<input type="number" min="0" step="1" value={draft.minimumAccountAgeMonths} onChange={(event) => setDraft({ ...draft, minimumAccountAgeMonths: event.target.value })} className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Entries per author<input type="number" min="1" max="5" step="1" value={draft.perAuthorLimit} onChange={(event) => setDraft({ ...draft, perAuthorLimit: event.target.value })} className={`${inputClass} mt-2`} /></label><label className="flex items-center gap-3 rounded-xl border border-[var(--border-default)] p-4 text-sm font-semibold text-[var(--text-secondary)]"><input type="checkbox" checked={draft.requireBio} onChange={(event) => setDraft({ ...draft, requireBio: event.target.checked })} />Require a completed profile bio</label></div><button disabled={busy} onClick={() => mutate(`/api/contests/${contest.slug}`, { requiredTopics: draft.requiredTopics.split(',').map((item) => item.trim()).filter(Boolean), allowedTargets: draft.allowedTargets.split(',').map((item) => item.trim()).filter(Boolean), perAuthorLimit: Number(draft.perAuthorLimit), eligibility: { minimumAccountAgeMonths: Number(draft.minimumAccountAgeMonths || 0), requireBio: draft.requireBio } }, 'PATCH', 'Eligibility saved.')} className="mt-6 rounded-full bg-[var(--accent)] px-6 py-2.5 text-sm font-bold text-white">Save eligibility</button></div>}
    {activeTab === 'schedule' && <div><h2 className="font-serif text-2xl font-bold text-[var(--text-primary)]">Contest schedule</h2><p className="mt-2 text-sm text-[var(--text-muted)]">Dates must remain in the future and lock when the contest opens or receives an entry.</p><div className="mt-6 grid gap-5"><label className="text-xs font-bold text-[var(--text-secondary)]">Contest starts<input type="datetime-local" value={draft.startsAt} onChange={(event) => setDraft({ ...draft, startsAt: event.target.value })} className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Submissions close<input type="datetime-local" value={draft.submissionsCloseAt} onChange={(event) => setDraft({ ...draft, submissionsCloseAt: event.target.value })} className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Judging closes<input type="datetime-local" value={draft.judgingClosesAt} onChange={(event) => setDraft({ ...draft, judgingClosesAt: event.target.value })} className={`${inputClass} mt-2`} /></label></div><button disabled={busy} onClick={() => mutate(`/api/contests/${contest.slug}`, { startsAt: draft.startsAt, submissionsCloseAt: draft.submissionsCloseAt, judgingClosesAt: draft.judgingClosesAt }, 'PATCH', 'Schedule saved.')} className="mt-6 rounded-full bg-[var(--accent)] px-6 py-2.5 text-sm font-bold text-white">Save schedule</button></div>}
    {activeTab === 'team' && <div><h2 className="font-serif text-2xl font-bold text-[var(--text-primary)]">Co-hosts and judges</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Invite by exact LixBlogs username. Co-hosts can maintain contest settings and operations; judges can review frozen entries and publish placements.</p><div className="mt-6 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)] p-5"><div className="grid gap-4"><label className="text-xs font-bold text-[var(--text-secondary)]">LixBlogs username<input value={member} onChange={(event) => setMember(event.target.value.replace(/^@/, ''))} className={`${inputClass} mt-2`} placeholder="username" /></label><label className="text-xs font-bold text-[var(--text-secondary)]">Contest role<select value={role} onChange={(event) => setRole(event.target.value)} className={`${inputClass} mt-2`}><option value="judge">Judge — review entries and select results</option><option value="moderator">Co-host — manage settings and operations</option></select></label><button disabled={!member || busy} onClick={() => mutate(`/api/contests/${contest.slug}/members`, { user: member, role }, 'POST', `@${member} invited as ${role === 'moderator' ? 'co-host' : 'judge'}.`)} className="w-fit rounded-xl bg-[var(--accent)] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Send invitation</button></div></div><ul className="mt-5 divide-y divide-[var(--divider)]">{members.map((item) => <li key={item.user_id} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-bold text-[var(--text-primary)]">@{item.username}</p><p className="mt-1 text-xs text-[var(--text-faint)]">{item.role === 'moderator' ? 'Co-host' : 'Judge'}</p></div><button onClick={() => mutate(`/api/contests/${contest.slug}/members?userId=${encodeURIComponent(item.user_id)}`, null, 'DELETE', 'Member removed.')} className="text-xs font-bold text-red-500">Remove</button></li>)}{!members.length && <li className="py-8 text-center text-sm text-[var(--text-muted)]">No co-hosts or judges assigned yet.</li>}</ul></div>}
    {activeTab === 'judging' && <div><h2 className="font-serif text-2xl font-bold text-[var(--text-primary)]">Judging and results</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Placements can be finalized only during judging. Review frozen snapshots before selecting winners.</p>{contest.status === 'judging' ? <div className="mt-6 grid gap-4">{[['Winner', winner, setWinner], ['Runner-up', runnerUp, setRunnerUp], ['Honorable mention', honorable, setHonorable]].map(([label, value, setter]) => <label key={label} className="text-xs font-bold text-[var(--text-secondary)]">{label}<select value={value} onChange={(event) => setter(event.target.value)} className={`${inputClass} mt-2`}><option value="">Not selected</option>{submissions.map((item) => <option key={item.id} value={item.id}>{item.title} — @{item.author.username}</option>)}</select></label>)}<button disabled={!winner || busy} onClick={() => mutate(`/api/contests/${contest.slug}/results`, { awards: [{ placement: 'winner', submissionId: winner }, ...(runnerUp ? [{ placement: 'runner-up', submissionId: runnerUp }] : []), ...(honorable ? [{ placement: 'honorable-mention', submissionId: honorable }] : [])], finalize: true }, 'POST', 'Results finalized.')} className="mt-2 rounded-full bg-amber-500 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">Finalize results</button></div> : <p className="mt-6 rounded-xl bg-[var(--bg-surface)] p-4 text-sm text-[var(--text-muted)]">Judging controls become available after submissions close.</p>}</div>}
    {activeTab === 'danger' && <div><h2 className="font-serif text-2xl font-bold text-red-500">Danger zone</h2><p className="mt-2 text-sm text-[var(--text-muted)]">These actions change or remove access for everyone. They are intentionally separated from normal settings.</p><div className="mt-6 divide-y divide-red-500/15 rounded-2xl border border-red-500/25">{!['cancelled', 'completed'].includes(contest.status) && <div className="flex flex-wrap items-center justify-between gap-4 p-5"><div><h3 className="text-sm font-bold text-[var(--text-primary)]">Cancel contest</h3><p className="mt-1 text-xs text-[var(--text-muted)]">Stop the lifecycle and prevent new submissions while preserving history.</p></div><button disabled={busy} onClick={() => window.confirm('Cancel this contest? Existing history will remain visible.') && mutate(`/api/contests/${contest.slug}`, { action: 'cancel' }, 'PATCH', 'Contest cancelled.')} className="rounded-full border border-red-500 px-4 py-2 text-xs font-bold text-red-500">Cancel contest</button></div>}{contest.configuredStatus === 'draft' && contest.viewerRole === 'organizer' && <div className="flex flex-wrap items-center justify-between gap-4 p-5"><div><h3 className="text-sm font-bold text-[var(--text-primary)]">Delete private draft</h3><p className="mt-1 text-xs text-[var(--text-muted)]">Permanently remove this unpublished contest and its setup.</p></div><button disabled={busy} onClick={() => window.confirm('Permanently delete this private contest draft? This cannot be undone.') && mutate(`/api/contests/${contest.slug}`, null, 'DELETE')} className="rounded-full bg-red-600 px-4 py-2 text-xs font-bold text-white">Delete draft</button></div>}</div></div>}
    {message && <p role="status" className={`mt-5 rounded-xl p-3 text-sm ${/failed|error|only|cannot/i.test(message) ? 'bg-red-500/10 text-red-500' : 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'}`}>{message}</p>}
      </div>
      <nav aria-label="Contest management sections" className="order-first flex gap-1 overflow-x-auto border-b border-[var(--divider)] bg-[var(--bg-surface)] p-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden lg:order-last lg:block lg:border-b-0 lg:border-l lg:p-4"><p className="hidden px-3 pb-3 pt-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--text-faint)] lg:block">Settings</p><div className="flex gap-1 lg:sticky lg:top-20 lg:block lg:space-y-1">{tabs.map((tab) => <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition lg:w-full ${activeTab === tab.id ? 'bg-[var(--accent-subtle)] text-[var(--accent)]' : 'text-[var(--text-muted)] hover:bg-[var(--card-bg)]'} ${tab.id === 'danger' ? 'lg:mt-5' : ''}`}><ion-icon name={tab.icon} /><span>{tab.label}</span></button>)}</div></nav>
    </div>
  </section>;
}
